
FROM python:3.10-slim as builder

WORKDIR /app


COPY requirements_all.txt .
RUN pip install --no-cache-dir --user -r requirements_all.txt


FROM python:3.10-slim

WORKDIR /app


COPY --from=builder /root/.local /root/.local

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    && apt-get clean

RUN pip install playwright \
    && playwright install chromium \
    && playwright install-deps chromium

# Copy application code
COPY . .


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]